# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alert.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AlertWindow(object):
    def setupUi(self, AlertWindow):
        AlertWindow.setObjectName("AlertWindow")
        AlertWindow.resize(569, 477)
        self.label_4 = QtWidgets.QLabel(AlertWindow)
        self.label_4.setGeometry(QtCore.QRect(70, 120, 54, 12))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.user_tip = QtWidgets.QLabel(AlertWindow)
        self.user_tip.setGeometry(QtCore.QRect(400, 60, 150, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.user_tip.setFont(font)
        self.user_tip.setStyleSheet("color: rgb(255, 1, 1);")
        self.user_tip.setText("")
        self.user_tip.setObjectName("user_tip")
        self.label = QtWidgets.QLabel(AlertWindow)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(70, 60, 54, 12))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.pass_tip = QtWidgets.QLabel(AlertWindow)
        self.pass_tip.setGeometry(QtCore.QRect(400, 120, 150, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pass_tip.setFont(font)
        self.pass_tip.setStyleSheet("color: rgb(255, 1, 1);")
        self.pass_tip.setText("")
        self.pass_tip.setObjectName("pass_tip")
        self.pass_alert_again_tip = QtWidgets.QLabel(AlertWindow)
        self.pass_alert_again_tip.setGeometry(QtCore.QRect(400, 220, 150, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pass_alert_again_tip.setFont(font)
        self.pass_alert_again_tip.setStyleSheet("color: rgb(255, 1, 1);")
        self.pass_alert_again_tip.setText("")
        self.pass_alert_again_tip.setObjectName("pass_alert_again_tip")
        self.label_5 = QtWidgets.QLabel(AlertWindow)
        self.label_5.setGeometry(QtCore.QRect(20, 220, 111, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.pass_alert_tip = QtWidgets.QLabel(AlertWindow)
        self.pass_alert_tip.setGeometry(QtCore.QRect(400, 170, 150, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pass_alert_tip.setFont(font)
        self.pass_alert_tip.setStyleSheet("color: rgb(255, 1, 1);")
        self.pass_alert_tip.setText("")
        self.pass_alert_tip.setObjectName("pass_alert_tip")
        self.label_6 = QtWidgets.QLabel(AlertWindow)
        self.label_6.setGeometry(QtCore.QRect(30, 160, 91, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.user_text = QtWidgets.QLineEdit(AlertWindow)
        self.user_text.setGeometry(QtCore.QRect(140, 50, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.user_text.setFont(font)
        self.user_text.setText("")
        self.user_text.setReadOnly(True)
        self.user_text.setObjectName("user_text")
        self.pass_text = QtWidgets.QLineEdit(AlertWindow)
        self.pass_text.setGeometry(QtCore.QRect(140, 110, 231, 31))
        self.pass_text.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_text.setObjectName("pass_text")
        self.pass_alert_text = QtWidgets.QLineEdit(AlertWindow)
        self.pass_alert_text.setGeometry(QtCore.QRect(140, 160, 231, 31))
        self.pass_alert_text.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_alert_text.setObjectName("pass_alert_text")
        self.pass_alert_again_text = QtWidgets.QLineEdit(AlertWindow)
        self.pass_alert_again_text.setGeometry(QtCore.QRect(140, 210, 231, 31))
        self.pass_alert_again_text.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_alert_again_text.setObjectName("pass_alert_again_text")
        self.AlertButton = QtWidgets.QPushButton(AlertWindow)
        self.AlertButton.setGeometry(QtCore.QRect(100, 300, 101, 51))
        self.AlertButton.setObjectName("AlertButton")
        self.ReturnButton = QtWidgets.QPushButton(AlertWindow)
        self.ReturnButton.setGeometry(QtCore.QRect(290, 300, 101, 51))
        self.ReturnButton.setObjectName("ReturnButton")

        self.retranslateUi(AlertWindow)
        QtCore.QMetaObject.connectSlotsByName(AlertWindow)

    def retranslateUi(self, AlertWindow):
        _translate = QtCore.QCoreApplication.translate
        AlertWindow.setWindowTitle(_translate("AlertWindow", "Form"))
        self.label_4.setText(_translate("AlertWindow", "密 码:"))
        self.label.setText(_translate("AlertWindow", "用户名:"))
        self.label_5.setText(_translate("AlertWindow", "确认修改后的密码："))
        self.label_6.setText(_translate("AlertWindow", "修改后的密码"))
        self.pass_text.setPlaceholderText(_translate("AlertWindow", "请输入你的密码"))
        self.pass_alert_text.setPlaceholderText(_translate("AlertWindow", "请输入修改后的密码"))
        self.pass_alert_again_text.setPlaceholderText(_translate("AlertWindow", "请再次确认你的密码"))
        self.AlertButton.setText(_translate("AlertWindow", "确认修改"))
        self.ReturnButton.setText(_translate("AlertWindow", "返回"))

