# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user-choose.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_yuangonghao(object):
    def setupUi(self, yuangonghao):
        yuangonghao.setObjectName("yuangonghao")
        yuangonghao.resize(814, 570)
        self.items_buttonx = QtWidgets.QGroupBox(yuangonghao)
        self.items_buttonx.setGeometry(QtCore.QRect(160, 60, 451, 151))
        self.items_buttonx.setTitle("")
        self.items_buttonx.setObjectName("items_buttonx")
        self.pushButton_7 = QtWidgets.QPushButton(self.items_buttonx)
        self.pushButton_7.setGeometry(QtCore.QRect(130, 90, 71, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.items_buttonx)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 90, 71, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.items_buttonx)
        self.pushButton_8.setGeometry(QtCore.QRect(220, 90, 71, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.items_buttonx)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 30, 71, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.items_buttonx)
        self.pushButton_4.setGeometry(QtCore.QRect(170, 30, 71, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.items_buttonx)
        self.pushButton_5.setGeometry(QtCore.QRect(270, 30, 71, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.items_buttonx)
        self.pushButton_9.setGeometry(QtCore.QRect(310, 90, 71, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.groupBox = QtWidgets.QGroupBox(yuangonghao)
        self.groupBox.setGeometry(QtCore.QRect(30, 240, 731, 301))
        self.groupBox.setObjectName("groupBox")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget_2.setGeometry(QtCore.QRect(330, 30, 371, 241))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(290, 30, 25, 241))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(30, 50, 111, 91))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 50, 111, 91))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 140, 111, 91))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 140, 111, 91))
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.retranslateUi(yuangonghao)
        QtCore.QMetaObject.connectSlotsByName(yuangonghao)

    def retranslateUi(self, yuangonghao):
        _translate = QtCore.QCoreApplication.translate
        yuangonghao.setWindowTitle(_translate("yuangonghao", "用户点菜"))
        self.pushButton_7.setText(_translate("yuangonghao", "红酒"))
        self.pushButton_6.setText(_translate("yuangonghao", "白酒"))
        self.pushButton_8.setText(_translate("yuangonghao", "啤酒"))
        self.pushButton_3.setText(_translate("yuangonghao", "热菜"))
        self.pushButton_4.setText(_translate("yuangonghao", "凉菜"))
        self.pushButton_5.setText(_translate("yuangonghao", "甜点"))
        self.pushButton_9.setText(_translate("yuangonghao", "饮料"))
        self.groupBox.setTitle(_translate("yuangonghao", "GroupBox"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("yuangonghao", "菜名一"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("yuangonghao", "菜名二"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("yuangonghao", "菜名三"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("yuangonghao", "菜名四"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("yuangonghao", "已点"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("yuangonghao", "数量"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("yuangonghao", "删除"))
        self.lineEdit.setText(_translate("yuangonghao", "一号菜"))
        self.lineEdit_2.setText(_translate("yuangonghao", "二号菜"))
        self.lineEdit_3.setText(_translate("yuangonghao", "三号菜"))
        self.lineEdit_4.setText(_translate("yuangonghao", "四号菜"))

